### ISSUE TITLE
lambda-inside-vpc

### ISSUE THREAD

**Issue by lukaspour** [telia-oss/terraform-aws-ecr-scanner#2]
AWS config rule lambda-inside-vpc requires VPC subnet IDs to be specified for each lambda function. https://docs.aws.amazon.com/config/latest/developerguide/lambda-inside-vpc.html
PR #1 fixes this issue.

**Comment by donramanauskas** [comment]
merged https://github.com/telia-oss/terraform-aws-ecr-scanner/pull/1
